#!/bin/bash

echo "Run this on the server to fix nginx configuration:"
echo ""
echo "# 1. Backup current nginx config"
echo "sudo cp /etc/nginx/sites-enabled/xbullet.me /etc/nginx/sites-enabled/xbullet.me.backup"
echo ""
echo "# 2. Create new nginx config"
echo "sudo cat > /etc/nginx/sites-available/xbullet.me << 'EOF'"
cat nginx-xbullet.conf
echo "EOF"
echo ""
echo "# 3. Test nginx configuration"
echo "sudo nginx -t"
echo ""
echo "# 4. Reload nginx"
echo "sudo systemctl reload nginx"
echo ""
echo "# 5. Test the endpoints"
echo "curl https://www.xbullet.me/api/health"