#!/bin/bash

echo "Run this after SSHing to the server:"
echo ""
echo "# 1. Kill process using port 8080"
echo "kill -9 \$(lsof -t -i:8080) 2>/dev/null || true"
echo ""
echo "# 2. Stop all running containers" 
echo "docker ps -q | xargs -r docker stop"
echo ""
echo "# 3. Find and deploy passport-buddy"
echo "cd /root"
echo "git clone https://github.com/Izaacapp/passport-buddy.git 2>/dev/null || true"
echo "cd passport-buddy"
echo ""
echo "# 4. Create .env.prod file"
echo "cat > .env.prod << 'EOF'"
cat .env.prod
echo "EOF"
echo ""
echo "# 5. Pull and run containers"
echo "docker-compose -f docker-compose.prod.yml pull"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo "docker-compose -f docker-compose.prod.yml logs --tail=50"