#!/bin/bash

# Passport Buddy Development Manager
# Ensures consistent development environment setup

set -e  # Exit on error

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Paths
PROJECT_ROOT="/Users/beck/github/mern&flutter"
BACKEND_DIR="$PROJECT_ROOT/backend"
FRONTEND_DIR="$PROJECT_ROOT/frontend"

# Functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed!"
        exit 1
    fi
    
    # Check Node
    if ! command -v node &> /dev/null; then
        log_error "Node.js is not installed!"
        exit 1
    fi
    
    # Check npm
    if ! command -v npm &> /dev/null; then
        log_error "npm is not installed!"
        exit 1
    fi
    
    log_success "All prerequisites installed"
}

check_mongodb() {
    log_info "Checking MongoDB container..."
    
    if docker ps | grep -q "mernflutter-mongo-1"; then
        log_success "MongoDB container is running"
        
        # Test connection
        if docker exec mernflutter-mongo-1 mongosh -u root -p pass --authenticationDatabase admin --eval "db.adminCommand('ping')" &> /dev/null; then
            log_success "MongoDB connection verified"
        else
            log_error "MongoDB authentication failed!"
            log_info "Restarting MongoDB container..."
            cd "$PROJECT_ROOT"
            docker-compose restart mongo
            sleep 5
        fi
    else
        log_warning "MongoDB container not running. Starting..."
        cd "$PROJECT_ROOT"
        docker-compose up -d mongo
        sleep 5
        
        # Verify it started
        if docker ps | grep -q "mernflutter-mongo-1"; then
            log_success "MongoDB container started"
        else
            log_error "Failed to start MongoDB container"
            exit 1
        fi
    fi
}

verify_env_files() {
    log_info "Verifying environment files..."
    
    # Backend .env
    if [ ! -f "$BACKEND_DIR/.env" ]; then
        log_warning "Creating backend .env file..."
        cat > "$BACKEND_DIR/.env" << 'EOF'
# Auto-generated by dev-manager.sh
NODE_ENV=development
PORT=3000
API_HOST=localhost

# MongoDB - Using Docker credentials
MONGO_URI=mongodb://root:pass@localhost:27017/passport_buddy?authSource=admin

# Security
JWT_SECRET=dev-secret-key-change-in-production
JWT_EXPIRES_IN=7d
JWT_COOKIE_EXPIRES_IN=7

# Email (using Resend)
EMAIL_PROVIDER=resend
RESEND_API_KEY=re_QqSxDnrK_FgNmb9qzdYxHLV8Y5yJJLawy
EMAIL_FROM=hello@xbullet.me
EMAIL_FROM_NAME=Passport Buddy

# Storage
STORAGE_TYPE=spaces
UPLOAD_DIR=./uploads
DO_SPACES_KEY=DO0026ZR2H3WW4F97N7K
DO_SPACES_SECRET=QrIZe6IGO3JgexBdpi3spPWNxIM61FExmySOcVKY9tA
DO_SPACES_ENDPOINT=nyc3.digitaloceanspaces.com
DO_SPACES_BUCKET=passportbuddy
DO_SPACES_REGION=nyc3

# Client URL
CLIENT_URL=http://localhost:3001,http://localhost:5173
EOF
        log_success "Backend .env created"
    else
        # Verify MongoDB connection string
        if ! grep -q "mongodb://root:pass@localhost:27017" "$BACKEND_DIR/.env"; then
            log_warning "Fixing MongoDB connection string in backend .env..."
            sed -i '' 's|MONGO_URI=.*|MONGO_URI=mongodb://root:pass@localhost:27017/passport_buddy?authSource=admin|' "$BACKEND_DIR/.env"
        fi
        log_success "Backend .env verified"
    fi
    
    # Frontend .env
    if [ ! -f "$FRONTEND_DIR/.env" ]; then
        log_warning "Creating frontend .env file..."
        cat > "$FRONTEND_DIR/.env" << 'EOF'
# Auto-generated by dev-manager.sh
VITE_API_URL=http://localhost:3000
VITE_GRAPHQL_URL=http://localhost:3000/graphql
VITE_AUTH_TOKEN_KEY=passport_buddy_token
VITE_AUTH_USER_KEY=passport_buddy_user
EOF
        log_success "Frontend .env created"
    else
        log_success "Frontend .env verified"
    fi
}

cleanup_ports() {
    log_info "Cleaning up existing processes..."
    
    # Kill processes on development ports
    for port in 3000 3001 5173; do
        if lsof -ti:$port > /dev/null 2>&1; then
            log_warning "Killing process on port $port"
            lsof -ti:$port | xargs kill -9 2>/dev/null || true
        fi
    done
    
    log_success "Ports cleaned up"
}

start_backend() {
    log_info "Starting backend server..."
    
    cd "$BACKEND_DIR"
    
    # Check if node_modules exists
    if [ ! -d "node_modules" ]; then
        log_warning "Installing backend dependencies..."
        npm install
    fi
    
    # Start backend
    nohup npm run dev > backend.log 2>&1 &
    BACKEND_PID=$!
    
    # Wait for backend to start
    log_info "Waiting for backend to start..."
    for i in {1..30}; do
        if curl -s http://localhost:3000/api/health > /dev/null 2>&1; then
            log_success "Backend is running on port 3000"
            return 0
        fi
        sleep 1
    done
    
    log_error "Backend failed to start!"
    tail -20 backend.log
    return 1
}

start_frontend() {
    log_info "Starting frontend server..."
    
    cd "$FRONTEND_DIR"
    
    # Check if node_modules exists
    if [ ! -d "node_modules" ]; then
        log_warning "Installing frontend dependencies..."
        npm install
    fi
    
    # Start frontend
    nohup npm run dev > frontend.log 2>&1 &
    FRONTEND_PID=$!
    
    # Wait for frontend to start
    log_info "Waiting for frontend to start..."
    for i in {1..30}; do
        if curl -s http://localhost:3001/ > /dev/null 2>&1; then
            log_success "Frontend is running on port 3001"
            return 0
        elif curl -s http://localhost:5173/ > /dev/null 2>&1; then
            log_success "Frontend is running on port 5173"
            return 0
        fi
        sleep 1
    done
    
    log_error "Frontend failed to start!"
    tail -20 frontend.log
    return 1
}

health_check() {
    log_info "Running health checks..."
    
    # Backend health
    if curl -s http://localhost:3000/api/health | jq . > /dev/null 2>&1; then
        log_success "Backend API: ✅ Healthy"
    else
        log_error "Backend API: ❌ Unhealthy"
    fi
    
    # Frontend health
    if curl -s http://localhost:3001/ > /dev/null 2>&1; then
        log_success "Frontend: ✅ Accessible"
    else
        log_error "Frontend: ❌ Not accessible"
    fi
    
    # MongoDB health
    if docker exec mernflutter-mongo-1 mongosh -u root -p pass --authenticationDatabase admin --eval "db.adminCommand('ping')" &> /dev/null; then
        log_success "MongoDB: ✅ Connected"
    else
        log_error "MongoDB: ❌ Connection failed"
    fi
}

show_status() {
    echo -e "\n${GREEN}=== Development Environment Status ===${NC}"
    echo -e "Frontend: ${BLUE}http://localhost:3001${NC}"
    echo -e "Backend:  ${BLUE}http://localhost:3000${NC}"
    echo -e "GraphQL:  ${BLUE}http://localhost:3000/graphql${NC}"
    echo -e "MongoDB:  ${BLUE}mongodb://localhost:27017${NC}"
    echo -e "\n${YELLOW}Commands:${NC}"
    echo -e "  View backend logs:  ${BLUE}tail -f $BACKEND_DIR/backend.log${NC}"
    echo -e "  View frontend logs: ${BLUE}tail -f $FRONTEND_DIR/frontend.log${NC}"
    echo -e "  Stop all:          ${BLUE}$0 stop${NC}"
    echo -e "  Health check:      ${BLUE}$0 health${NC}"
}

stop_all() {
    log_info "Stopping all services..."
    
    # Kill node processes
    pkill -f "node.*server.ts" 2>/dev/null || true
    pkill -f "vite" 2>/dev/null || true
    
    # Clean up ports
    cleanup_ports
    
    log_success "All services stopped"
}

# Main script
case "${1:-start}" in
    start)
        echo -e "${GREEN}🚀 Starting Passport Buddy Development Environment${NC}\n"
        
        check_prerequisites
        check_mongodb
        verify_env_files
        cleanup_ports
        
        if start_backend && start_frontend; then
            health_check
            show_status
            
            # Keep script running
            trap "stop_all; exit" INT TERM
            log_info "Press Ctrl+C to stop all services"
            wait
        else
            log_error "Failed to start services!"
            stop_all
            exit 1
        fi
        ;;
        
    stop)
        stop_all
        ;;
        
    restart)
        stop_all
        sleep 2
        exec "$0" start
        ;;
        
    health)
        health_check
        ;;
        
    status)
        health_check
        show_status
        ;;
        
    *)
        echo "Usage: $0 {start|stop|restart|health|status}"
        exit 1
        ;;
esac