// Demo users with realistic travel profiles
import { profilePictures } from './profilePictures';

export const demoUsers = [
  {
    _id: '1',
    id: '1',
    username: 'wanderlust_beck',
    email: 'demo@passport-buddy.com',
    name: 'Beck Johnson',
    fullName: 'Beck Johnson',
    avatar: profilePictures.beck,
    bio: '✈️ Founder of Passport Buddy | 50+ countries | Building the future of travel',
    profilePicture: profilePictures.beck,
    followersCount: 15420,
    followingCount: 892,
    isVerified: true,
    emailVerified: true,
    location: 'San Francisco, CA',
    homeAirport: 'SFO',
    passportCountry: 'USA',
    milesFlown: 524300,
    countriesVisited: ['USA', 'Japan', 'Thailand', 'UAE', 'UK', 'France', 'Italy', 'Spain', 'Mexico', 'Canada'],
    createdAt: new Date('2023-01-15').toISOString()
  },
  {
    _id: '2',
    id: '2',
    username: 'sarah_explores',
    email: 'sarah@demo.com',
    name: 'Sarah Chen',
    fullName: 'Sarah Chen',
    avatar: profilePictures.sarah,
    bio: '🌏 Travel blogger | Photography enthusiast | Chasing sunsets around the world',
    profilePicture: profilePictures.sarah,
    followersCount: 8934,
    followingCount: 567,
    isVerified: true,
    emailVerified: true,
    location: 'New York, NY',
    homeAirport: 'JFK',
    passportCountry: 'USA',
    milesFlown: 287600,
    countriesVisited: ['China', 'Japan', 'Korea', 'Singapore', 'Australia', 'New Zealand'],
    createdAt: new Date('2023-03-20').toISOString()
  },
  {
    _id: '3',
    id: '3',
    username: 'pilot_mike',
    email: 'mike@demo.com',
    name: 'Mike Thompson',
    fullName: 'Mike Thompson',
    avatar: profilePictures.mike,
    bio: '👨‍✈️ Commercial pilot | United Airlines | Living above the clouds',
    profilePicture: profilePictures.mike,
    followersCount: 12567,
    followingCount: 342,
    isVerified: true,
    emailVerified: true,
    location: 'Chicago, IL',
    homeAirport: 'ORD',
    passportCountry: 'USA',
    milesFlown: 2847300,
    countriesVisited: ['Too many to count!'],
    createdAt: new Date('2023-02-10').toISOString()
  },
  {
    _id: '4',
    id: '4',
    username: 'adventure_emma',
    email: 'emma@demo.com',
    name: 'Emma Rodriguez',
    fullName: 'Emma Rodriguez',
    avatar: profilePictures.emma,
    bio: '🎒 Backpacker | Solo traveler | Mountains > Beaches',
    profilePicture: profilePictures.emma,
    followersCount: 5678,
    followingCount: 890,
    isVerified: false,
    emailVerified: true,
    location: 'Denver, CO',
    homeAirport: 'DEN',
    passportCountry: 'USA',
    milesFlown: 156700,
    countriesVisited: ['Peru', 'Nepal', 'Switzerland', 'Norway', 'Chile'],
    createdAt: new Date('2023-04-05').toISOString()
  },
  {
    _id: '5',
    id: '5',
    username: 'alex_in_asia',
    email: 'alex@demo.com',
    name: 'Alex Kim',
    fullName: 'Alex Kim',
    avatar: profilePictures.alex,
    bio: '🍜 Food & travel | Currently: Bangkok | Next: Seoul',
    profilePicture: profilePictures.alex,
    followersCount: 9012,
    followingCount: 1234,
    isVerified: true,
    emailVerified: true,
    location: 'Bangkok, Thailand',
    homeAirport: 'BKK',
    passportCountry: 'South Korea',
    milesFlown: 198400,
    countriesVisited: ['Thailand', 'Vietnam', 'Cambodia', 'Malaysia', 'Indonesia'],
    createdAt: new Date('2023-05-12').toISOString()
  },
  {
    _id: '6',
    id: '6',
    username: 'luxury_travels_james',
    email: 'james@demo.com',
    name: 'James Williams',
    fullName: 'James Williams',
    avatar: profilePictures.james,
    bio: '🥂 Luxury travel consultant | First class reviews | Hotels & lounges',
    profilePicture: profilePictures.james,
    followersCount: 23456,
    followingCount: 456,
    isVerified: true,
    emailVerified: true,
    location: 'London, UK',
    homeAirport: 'LHR',
    passportCountry: 'UK',
    milesFlown: 892300,
    countriesVisited: ['UAE', 'Singapore', 'Japan', 'France', 'USA', 'Australia'],
    createdAt: new Date('2023-01-28').toISOString()
  },
  {
    _id: '7',
    id: '7',
    username: 'nina_nomad',
    email: 'nina@demo.com',
    name: 'Nina Patel',
    fullName: 'Nina Patel',
    avatar: profilePictures.nina,
    bio: '🌺 Digital nomad | Remote work advocate | Coffee shops worldwide',
    profilePicture: profilePictures.nina,
    followersCount: 7890,
    followingCount: 678,
    isVerified: false,
    emailVerified: true,
    location: 'Bali, Indonesia',
    homeAirport: 'DPS',
    passportCountry: 'India',
    milesFlown: 234500,
    countriesVisited: ['Indonesia', 'Thailand', 'Portugal', 'Mexico', 'Turkey'],
    createdAt: new Date('2023-06-18').toISOString()
  },
  {
    _id: '8',
    id: '8',
    username: 'captain_olivia',
    email: 'olivia@demo.com',
    name: 'Olivia Martinez',
    fullName: 'Olivia Martinez',
    avatar: profilePictures.olivia,
    bio: '✈️ Emirates A380 Captain | Breaking barriers at 30,000 feet',
    profilePicture: profilePictures.olivia,
    followersCount: 34567,
    followingCount: 234,
    isVerified: true,
    emailVerified: true,
    location: 'Dubai, UAE',
    homeAirport: 'DXB',
    passportCountry: 'Spain',
    milesFlown: 3456700,
    countriesVisited: ['Everywhere Emirates flies!'],
    createdAt: new Date('2023-02-22').toISOString()
  },
  {
    _id: '9',
    id: '9',
    username: 'budget_traveler_raj',
    email: 'raj@demo.com',
    name: 'Raj Sharma',
    fullName: 'Raj Sharma',
    avatar: profilePictures.raj,
    bio: '💰 Budget travel hacks | Hostels & street food | $50/day challenge',
    profilePicture: profilePictures.raj,
    followersCount: 4567,
    followingCount: 789,
    isVerified: false,
    emailVerified: true,
    location: 'Mumbai, India',
    homeAirport: 'BOM',
    passportCountry: 'India',
    milesFlown: 89300,
    countriesVisited: ['Sri Lanka', 'Nepal', 'Bangladesh', 'Thailand', 'Malaysia'],
    createdAt: new Date('2023-07-30').toISOString()
  },
  {
    _id: '10',
    id: '10',
    username: 'island_hopper_lisa',
    email: 'lisa@demo.com',
    name: 'Lisa Anderson',
    fullName: 'Lisa Anderson',
    avatar: profilePictures.lisa,
    bio: '🏝️ Island specialist | Diving instructor | Ocean conservation',
    profilePicture: profilePictures.lisa,
    followersCount: 6789,
    followingCount: 543,
    isVerified: true,
    emailVerified: true,
    location: 'Honolulu, HI',
    homeAirport: 'HNL',
    passportCountry: 'USA',
    milesFlown: 345600,
    countriesVisited: ['Maldives', 'Seychelles', 'Fiji', 'Tahiti', 'Philippines'],
    createdAt: new Date('2023-08-14').toISOString()
  },
  {
    _id: '11',
    id: '11',
    username: 'marcus_miles',
    email: 'marcus@demo.com',
    name: 'Marcus Johnson',
    fullName: 'Marcus Johnson',
    avatar: profilePictures.marcus,
    bio: '🎯 Points & miles expert | Credit card churning | Free flights guru',
    profilePicture: profilePictures.marcus,
    followersCount: 18900,
    followingCount: 432,
    isVerified: true,
    emailVerified: true,
    location: 'Atlanta, GA',
    homeAirport: 'ATL',
    passportCountry: 'USA',
    milesFlown: 678900,
    countriesVisited: ['All on points!'],
    createdAt: new Date('2023-03-08').toISOString()
  }
];